Make sure escape value before appendChild() for XML formatter
zendframework/zend-log pull request #67
Opened 2016-12-27 15:24 UTC by samsonasik

to avoid error: " DOMElement::__construct(): unterminated entity reference"

2016-12-29 05:06 UTC, samsonasik commented
I added test that include escape "&" to "&amp;"

2016-12-29 07:34 UTC, Ocramius requested changes

2016-12-29 07:34 UTC, Ocramius commented on test/Formatter/XmlTest.php
> +        $expected = '<logEntry><timestamp>2001-01-01T12:00:00-06:00</timestamp><message>test</message><priority>1</priority><priorityName>CRIT</priorityName><extra><test><one/><two><three><four>four<
Escaping seems wrong here, no? `<test_object>&amp;quot;Object&amp;quot;`, specifically

2016-12-29 07:43 UTC, samsonasik commented on test/Formatter/XmlTest.php
> +        $expected = '<logEntry><timestamp>2001-01-01T12:00:00-06:00</timestamp><message>test</message><priority>1</priority><priorityName>CRIT</priorityName><extra><test><one/><two><three><four>four<
@Ocramius fixed now ;)

2016-12-30 15:48 UTC, Ocramius approved these changes

2017-01-11 12:02 UTC, froschdesign approved these changes

2017-05-17 11:05 UTC, samsonasik commented
is there any chance to get it merged ? Thank you.

2017-05-17 13:39 UTC, merged

2017-05-17 13:39 UTC, weierophinney commented
Thanks, @samsonasik