Add a formatter to compactly print stack traces
zendframework/zend-log pull request #78
Opened 2017-10-11 16:16 UTC by Erikvv

Produces a similar format to the native PHP exception handler

Could use some more tests.
The type of the exception is not printed, it is not available.

Solves #32 if you use this formatter

2017-10-12 06:33 UTC, zf2timo commented
You changed the php constrained in the `composer.json`, so the `.travis.yml` also have to be updated.

2017-10-12 06:58 UTC, froschdesign commented
@Erikvv and @zf2timo 
> You changed the php constrained in the composer.json, so the .travis.yml also have to be updated.

Please open a new PR for these changes!

2017-10-12 07:30 UTC, froschdesign requested changes

2017-10-12 07:30 UTC, froschdesign commented on src/Formatter/NativeException.php
> +        $output = '[' . $event['timestamp'] . '] ' . $event['priorityName'] . ' ('
These lines are very hard to read. Please use `sprintf`.

2017-10-12 07:30 UTC, froschdesign commented on src/Formatter/NativeException.php
> +                $output .= "#$i " . $this->formatTraceLine($traceLine) . "\n";
Same here. (Don't use `"#$i "`.)

2017-10-12 07:30 UTC, froschdesign commented on src/Formatter/NativeException.php
> +     * {@inheritDoc}
Please remove the brackets.

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#61-making-inheritance-explicit-using-the-inheritdoc-tag

2017-10-12 07:30 UTC, froschdesign commented on src/Formatter/NativeException.php
> +     * {@inheritDoc}
Same here.

2017-10-12 07:30 UTC, froschdesign commented on src/Formatter/NativeException.php
> + * Zend Framework (http://framework.zend.com/)
Please replace the header with this:

```php
/**
 * @see       https://github.com/zendframework/zend-log for the canonical source repository
 * @copyright Copyright (c) 2015-2017 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   https://github.com/zendframework/zend-log/blob/master/LICENSE.md New BSD License
 */
```

2017-10-12 07:30 UTC, froschdesign commented on test/Formatter/NativeExceptionTest.php
> + * Zend Framework (http://framework.zend.com/)
Please replace the header with this:

```php
/**
 * @see       https://github.com/zendframework/zend-log for the canonical source repository
 * @copyright Copyright (c) 2015-2017 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   https://github.com/zendframework/zend-log/blob/master/LICENSE.md New BSD License
 */
```

2017-10-13 09:41 UTC, Erikvv commented
Bit of a misunderstanding, turns out our company will not be using this library in the near future.

I'm closing the PR.

2017-10-13 09:41 UTC, closed without merging